sudo: required # needed for trusty beta
dist: trusty   # needed for HarfBuzz

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo add-apt-repository ppa:as-bahanta/raqm -y;
      sudo apt-get update -qq;
      sudo apt-get install -y libfreetype6-dev libharfbuzz-dev libfribidi-dev libglib2.0-dev gtk-doc-tools;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install freetype fribidi glib gtk-doc;
      brew install --without-icu4c --without-glib --without-gobject-introspection harfbuzz;
      export XML_CATALOG_FILES="/usr/local/etc/xml/catalog";
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" -a "${CC}" == "gcc" ]; then export CC=gcc-4.8; fi

script:
  - wget https://github.com/adah1972/libunibreak/releases/download/libunibreak_4_0/libunibreak-4.0.tar.gz
  - (tar xf libunibreak-4.0.tar.gz && cd libunibreak-4.0 && ./configure && make && sudo make install)
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ldconfig; fi
  - ./autogen.sh
  - ./configure --enable-gtk-doc
  - make
  - make check
  - make distcheck

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CC" == "gcc" -a "$TRAVIS_SECURE_ENV_VARS" == "true" ];
      then bash .ci/deploy-docs.sh;
    fi

notifications:
  email:
    recipients:
      - host-oman@googlegroups.com
